server:
  port: 8607
#spring
spring:
  datasource:
    url: jdbc:mysql://60.205.212.221:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cx86452.
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jmx:
    default-domain: blog-admin
  thymeleaf:
    cache: true   #关闭缓存
  application:
    name: blog-admin
  #redis
  redis:
    host: 127.0.0.1 #redis的主机ip
    port: 6379
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath*:com.starriver.blog.dao/*.xml